src/main/java/ch/ultrasoft/web/KonsultationBean.java
package ch.ultrasoft.web;

import ch.ultrasoft.domain.AufenthaltEntity;
import ch.ultrasoft.domain.KonsultationEntity;
import ch.ultrasoft.domain.PersonEntity;
import ch.ultrasoft.service.AufenthaltService;
import ch.ultrasoft.service.KonsultationService;
import ch.ultrasoft.service.PersonService;
import ch.ultrasoft.web.util.MessageFactory;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

import org.primefaces.event.TransferEvent;
import org.primefaces.model.DualListModel;

@Named("konsultationBean")
@ViewScoped
public class KonsultationBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(KonsultationBean.class.getName());
    
    private List<KonsultationEntity> konsultationList;

    private KonsultationEntity konsultation;
    
    @Inject
    private KonsultationService konsultationService;
    
    @Inject
    private PersonService personService;
    
    @Inject
    private AufenthaltService aufenthaltService;
    
    private DualListModel<PersonEntity> personens;
    private List<String> transferedPersonenIDs;
    private List<String> removedPersonenIDs;
    
    private List<AufenthaltEntity> allAufenthaltsList;
    
    public void prepareNewKonsultation() {
        reset();
        this.konsultation = new KonsultationEntity();
        // set any default values now, if you need
        // Example: this.konsultation.setAnything("test");
    }

    public String persist() {

        String message;
        
        try {
            
            if (konsultation.getId() != null) {
                konsultation = konsultationService.update(konsultation);
                message = "message_successfully_updated";
            } else {
                konsultation = konsultationService.save(konsultation);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        
        konsultationList = null;

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        
        return null;
    }
    
    public String delete() {
        
        String message;
        
        try {
            konsultationService.delete(konsultation);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));
        
        return null;
    }
    
    public void onDialogOpen(KonsultationEntity konsultation) {
        reset();
        this.konsultation = konsultation;
    }
    
    public void reset() {
        konsultation = null;
        konsultationList = null;
        
        personens = null;
        transferedPersonenIDs = null;
        removedPersonenIDs = null;
        
        allAufenthaltsList = null;
        
    }

    // Get a List of all aufenthalt
    public List<AufenthaltEntity> getAufenthalts() {
        if (this.allAufenthaltsList == null) {
            this.allAufenthaltsList = aufenthaltService.findAllAufenthaltEntities();
        }
        return this.allAufenthaltsList;
    }
    
    // Update aufenthalt of the current konsultation
    public void updateAufenthalt(AufenthaltEntity aufenthalt) {
        this.konsultation.setAufenthalt(aufenthalt);
        // Maybe we just created and assigned a new aufenthalt. So reset the allAufenthaltList.
        allAufenthaltsList = null;
    }
    
    public DualListModel<PersonEntity> getPersonens() {
        return personens;
    }

    public void setPersonens(DualListModel<PersonEntity> persons) {
        this.personens = persons;
    }
    
    public List<PersonEntity> getFullPersonensList() {
        List<PersonEntity> allList = new ArrayList<>();
        allList.addAll(personens.getSource());
        allList.addAll(personens.getTarget());
        return allList;
    }
    
    public void onPersonensDialog(KonsultationEntity konsultation) {
        // Prepare the personen PickList
        this.konsultation = konsultation;
        List<PersonEntity> selectedPersonsFromDB = personService
                .findPersonensByKonsultation(this.konsultation);
        List<PersonEntity> availablePersonsFromDB = personService
                .findAvailablePersonens(this.konsultation);
        this.personens = new DualListModel<>(availablePersonsFromDB, selectedPersonsFromDB);
        
        transferedPersonenIDs = new ArrayList<>();
        removedPersonenIDs = new ArrayList<>();
    }
    
    public void onPersonensPickListTransfer(TransferEvent event) {
        // If a personen is transferred within the PickList, we just transfer it in this
        // bean scope. We do not change anything it the database, yet.
        for (Object item : event.getItems()) {
            String id = ((PersonEntity) item).getId().toString();
            if (event.isAdd()) {
                transferedPersonenIDs.add(id);
                removedPersonenIDs.remove(id);
            } else if (event.isRemove()) {
                removedPersonenIDs.add(id);
                transferedPersonenIDs.remove(id);
            }
        }
        
    }
    
    public void updatePersonen(PersonEntity person) {
        // If a new personen is created, we persist it to the database,
        // but we do not assign it to this konsultation in the database, yet.
        personens.getTarget().add(person);
        transferedPersonenIDs.add(person.getId().toString());
    }
    
    public void onPersonensSubmit() {
        // Now we save the changed of the PickList to the database.
        try {
            
            List<PersonEntity> selectedPersonsFromDB = personService.findPersonensByKonsultation(this.konsultation);
            List<PersonEntity> availablePersonsFromDB = personService.findAvailablePersonens(this.konsultation);

            // Because personens are lazily loaded, we need to fetch them now
            this.konsultation = konsultationService.fetchPersonens(this.konsultation);
            
            for (PersonEntity person : selectedPersonsFromDB) {
                if (removedPersonenIDs.contains(person.getId().toString())) {
                    
                    this.konsultation.getPersonens().remove(person);
                    
                }
            }
    
            for (PersonEntity person : availablePersonsFromDB) {
                if (transferedPersonenIDs.contains(person.getId().toString())) {
                    
                    this.konsultation.getPersonens().add(person);
                    
                }
            }
            
            this.konsultation = konsultationService.update(this.konsultation);
            
            FacesMessage facesMessage = MessageFactory.getMessage("message_changes_saved");
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            
            reset();

        } catch (OptimisticLockException e) {
            FacesMessage facesMessage = MessageFactory.getMessage(
                    "message_optimistic_locking_exception");
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            FacesMessage facesMessage = MessageFactory.getMessage(
                    "message_picklist_save_exception");
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
    }
    
    public KonsultationEntity getKonsultation() {
        if (this.konsultation == null) {
            prepareNewKonsultation();
        }
        return this.konsultation;
    }
    
    public void setKonsultation(KonsultationEntity konsultation) {
        this.konsultation = konsultation;
    }
    
    public List<KonsultationEntity> getKonsultationList() {
        if (konsultationList == null) {
            konsultationList = konsultationService.findAllKonsultationEntities();
        }
        return konsultationList;
    }

    public void setKonsultationList(List<KonsultationEntity> konsultationList) {
        this.konsultationList = konsultationList;
    }
    
}

src/main/webapp/pages/konsultation/konsultation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">

    <h:form prependId="false" id="konsultationDataForm" onkeypress="if (event.keyCode == 13) {return false; }">

        <p:dataTable id="konsultationTable" value="#{konsultationBean.konsultationList}" var="konsultation" resizableColumns="true" paginator="true"
                paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true"
                paginatorPosition="bottom" widgetVar="konsultationTable" emptyMessage="#{messages.label_no_records_found}"
                reflow="true">
        
          <f:facet name="header" >

              <p:commandButton value="#{messages.create_new_konsultation}" icon="ui-icon-plusthick" action="#{konsultationBean.prepareNewKonsultation()}"
                      resetValues="true" update=":editKonsultationDialog" oncomplete="PF('editKonsultationDialogWidget').show()"
                      style="float:left" />
              
              <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
              <p:columnToggler datasource="konsultationTable" trigger="toggler" />
          </f:facet>
          
          <p:column headerText="#{messages.field_label_konsultation_von}" sortBy="#{konsultation.von}" filterBy="#{konsultation.von}">
            <f:facet name="filter">
                <p:inputText id="vonFilter"
                        onkeyup="if (event.keyCode == 13) {PF('konsultationTable').filter(); updateVonFilter(); return false;}" >
                    <p:remoteCommand name="updateVonFilter" update="konsultationTable:vonFilter" />
                    <f:convertDateTime />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{konsultation.von}"><f:convertDateTime /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_konsultation_bis}" sortBy="#{konsultation.bis}" filterBy="#{konsultation.bis}">
            <f:facet name="filter">
                <p:inputText id="bisFilter"
                        onkeyup="if (event.keyCode == 13) {PF('konsultationTable').filter(); updateBisFilter(); return false;}" >
                    <p:remoteCommand name="updateBisFilter" update="konsultationTable:bisFilter" />
                    <f:convertDateTime />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{konsultation.bis}"><f:convertDateTime /></h:outputText>
          </p:column>

          <p:column  headerText="#{messages.field_label_konsultation_text}" sortBy="#{konsultation.text}" filterBy="#{konsultation.text}">
            <f:facet name="filter">
                <p:inputText id="textFilter"
                        onkeypress="if (event.keyCode == 13) {PF('konsultationTable').filter(); updateTextFilter(); return false; }" >
                    <p:remoteCommand name="updateTextFilter" update="konsultationTable:textFilter" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{konsultation.text}" />
          </p:column>

          <p:column headerText="#{messages.field_label_konsultation_aufenthalt}" sortBy="#{konsultation.aufenthalt}" filterBy="#{konsultation.aufenthalt}">
            <f:facet name="filter">
            <p:selectOneMenu  id="aufenthaltFilter"
                            style="width:145px;"
                            onchange="PF('konsultationTable').filter(); return false;">
                <f:selectItem noSelectionOption="true" itemLabel="" />
                <f:selectItems itemLabel="#{aufenthalt.id}"
                            value="#{konsultationBean.aufenthalts}" 
                            var="aufenthalt" 
                            itemValue="#{aufenthalt}" />
                <o:converter converterId="omnifaces.SelectItemsConverter" list="#{konsultationBean.aufenthalts}" />
            </p:selectOneMenu>
            </f:facet>
            <h:outputText value="#{konsultation.aufenthalt.id}" />
          </p:column>

          <p:column headerText="#{messages.field_label_konsultation_personen_plural}" styleClass="action-column" exportable="false">
            
            <p:commandButton icon="ui-icon-transfer-e-w"  title="#{messages.field_label_konsultation_personen_plural}" action="#{konsultationBean.onPersonensDialog(konsultation)}" oncomplete="PF('konsultationPersonensDialogWidget').show()" update=":konsultationPersonensDialog"/>
            
          </p:column>
          
          <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">
            
            <p:commandButton icon="ui-icon-zoomin" update=":viewKonsultationDialog" oncomplete="PF('viewKonsultationDialogWidget').show()" title="#{messages.label_view}">
              <f:setPropertyActionListener value="#{konsultation}" target="#{konsultationBean.konsultation}" />
            </p:commandButton>

            <p:commandButton icon="ui-icon-pencil" update=":editKonsultationDialog"
                resetValues="true" 
                action="#{konsultationBean.onDialogOpen(konsultation)}"
                oncomplete="PF('editKonsultationDialogWidget').show()"
                title="#{messages.label_edit}" >
            </p:commandButton>

            <p:commandButton icon="ui-icon-close" 
                oncomplete="PF('deleteKonsultationDialogWidget').show()"
                title="#{messages.label_delete}" >
                <f:setPropertyActionListener value="#{konsultation}"
                    target="#{konsultationBean.konsultation}" />
            </p:commandButton>
    
          </p:column>
          
        </p:dataTable>
        
    </h:form>

    <p:confirmDialog id="deleteKonsultationDialog" widgetVar="deleteKonsultationDialogWidget"
        header="#{messages.label_confirm_deletion}"
        severity="alarm">
        <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
        <p:outputPanel>
          <h:form>
            <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_yes}" action="#{konsultationBean.delete}" update=":konsultationDataForm :growlForm:growl" oncomplete="PF('deleteKonsultationDialogWidget').hide()" />
              <p:commandButton value="#{messages.label_no}" onclick="PF('deleteKonsultationDialogWidget').hide()" type="button" />
            </div>
          </h:form>
        </p:outputPanel>
    </p:confirmDialog>
    
    <p:dialog dynamic="true" id="editKonsultationDialog" header="#{messages.label_konsultation_caption}"
            modal="true" widgetVar="editKonsultationDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{konsultationBean.reset}"/>
        <h:form id="editKonsultationForm" >
            <p:outputPanel id="konsultationEditPanel">
                <ui:include src="/pages/konsultation/konsultationEditInclude.xhtml"/>
                <div style="text-align: center; margin:10px">
                    <p:commandButton value="#{messages.label_save}"
                            icon="ui-icon-disk" action="#{konsultationBean.persist}"
                            update=":editKonsultationForm:konsultationEditPanel :konsultationDataForm :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('editKonsultationDialogWidget').hide()" />
                    <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('editKonsultationDialogWidget').hide()" type="button" />
                </div>
            </p:outputPanel>
        </h:form>
    </p:dialog>
    
    <p:dialog dynamic="true" id="viewKonsultationDialog" header="#{messages.label_konsultation_caption}" modal="true" widgetVar="viewKonsultationDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{konsultationBean.reset}" />
        <h:form id="viewKonsultationForm">
          <ui:include src="/pages/konsultation/konsultationViewInclude.xhtml"/>
          <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('viewKonsultationDialogWidget').hide()" type="button" />
          </div>
        </h:form>
    </p:dialog>
    
    <p:dialog dynamic="true" id="createAufenthaltFromEditDialog"
        header="#{messages.dialog_konsultation_create_aufenthalt}" modal="true"
        widgetVar="createAufenthaltFromEditDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{aufenthaltBean.reset}" />
        <p:outputPanel id="createAufenthaltPanel">
                <h:form id="createAufenthaltForm">
                    <ui:include src="/pages/aufenthalt/aufenthaltEditInclude.xhtml">
                        <ui:param name="hideKonsultationSelectInput" value="true" />
                    </ui:include>
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton
                            action="#{konsultationBean.updateAufenthalt(aufenthaltBean.aufenthalt)}"
                            value="#{messages.label_save}" icon="ui-icon-disk"
                            actionListener="#{aufenthaltBean.persist}"
                            update=":editKonsultationForm:aufenthaltSelectInput :createAufenthaltPanel :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('createAufenthaltFromEditDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_close}"
                            icon="ui-icon-close"
                            onclick="PF('createAufenthaltFromEditDialogWidget').hide()"
                            type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
    </p:dialog>
    
    <p:dialog dynamic="true" id="konsultationPersonensDialog" header="#{messages.dialog_header_konsultation_personen_plural}" modal="true" widgetVar="konsultationPersonensDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{konsultationBean.reset}" />
        <p:outputPanel id="konsultationPersonensPanel">
            <h:form id="konsultationPersonensForm">
                <ui:include src="/pages/konsultation/konsultationPersonenInclude.xhtml" />
                <div style="text-align: center; margin:10px">
                    <p:commandButton value="#{messages.label_save}"
                        icon="ui-icon-disk"
                        action="#{konsultationBean.onPersonensSubmit}"
                        update=":growlForm:growl"
                        oncomplete="if(!args.validationFailed) PF('konsultationPersonensDialogWidget').hide()"
                        partialSubmit="true" process="@this" />
                    <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('konsultationPersonensDialogWidget').hide()" type="button" />
                </div>
            </h:form>
        </p:outputPanel>
    </p:dialog>
    
    <p:dialog dynamic="true" id="createPersonenDialog"
        header="#{messages.dialog_konsultation_create_personen}" modal="true"
        widgetVar="createPersonenDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{personBean.reset}" />
        <p:outputPanel id="createPersonenPanel">
                <h:form id="createPersonenForm">
                    <ui:include src="/pages/person/personEditInclude.xhtml">
                        <ui:param name="hideKonsultationSelectInput" value="true" />
                    </ui:include>
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton
                            action="#{konsultationBean.updatePersonen(personBean.person)}"
                            value="#{messages.label_save}" icon="ui-icon-disk"
                            actionListener="#{personBean.persist}"
                            update=":konsultationPersonensPanel :createPersonenPanel :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('createPersonenDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_close}"
                            icon="ui-icon-close"
                            onclick="PF('createPersonenDialogWidget').hide()"
                            type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
    </p:dialog>
    
  </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/konsultation/konsultationEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

        <p:outputPanel styleClass="ui-fluid">

            <p:panelGrid columns="3" columnClasses="ui-grid-col-4,ui-grid-col-6,ui-grid-col-2" layout="grid" style="max-width:400px">
            
                <h:outputLabel value="#{messages.field_label_konsultation_von}:" for="vonEditInput" />
                <p:calendar id="vonEditInput" navigator="true" value="#{konsultationBean.konsultation.von}" label="#{messages.field_label_konsultation_von}" />
                <p:message for="vonEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_konsultation_bis}:" for="bisEditInput" />
                <p:calendar id="bisEditInput" navigator="true" value="#{konsultationBean.konsultation.bis}" label="#{messages.field_label_konsultation_bis}" />
                <p:message for="bisEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_konsultation_text}:" for="textEditInput" />
                <p:inputText value="#{konsultationBean.konsultation.text}" id="textEditInput" 
                    label="#{messages.field_label_konsultation_text}" />
                <p:message for="textEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_konsultation_aufenthalt}:" for="aufenthaltSelectInput" rendered="#{not hideAufenthaltSelectInput}"/>
                <h:panelGroup rendered="#{not hideAufenthaltSelectInput}">
                    <p:selectOneMenu value="#{konsultationBean.konsultation.aufenthalt}"
                                    id="aufenthaltSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{konsultationBean.aufenthalts}" 
                                    var="aufenthalt" 
                                    itemLabel="#{aufenthalt.id}"
                                    itemValue="#{aufenthalt}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{konsultationBean.aufenthalts}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hideAufenthaltSelectInput}">
                
                    <p:commandButton icon="ui-icon-plusthick" title="#{messages.label_create}"
                              action="#{aufenthaltBean.prepareNewAufenthalt()}"
                              update=":createAufenthaltFromEditDialog"
                              resetValues="true"
                              oncomplete="PF('createAufenthaltFromEditDialogWidget').show()"
                              rendered="#{applicationBean.componentExists('createAufenthaltFromEditDialog')}"
                              style="vertical-align:top;" partialSubmit="true" process="@this">
                    </p:commandButton>
                    
                    <p:message for="aufenthaltSelectInput" display="icon" rendered="#{not hideAufenthaltSelectInput}"/>
                </h:panelGroup>
                
            </p:panelGrid>

        </p:outputPanel>
</html>

src/main/webapp/pages/konsultation/konsultationPersonenInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
      
    <h:panelGrid >
       
       <p:commandButton value="#{messages.dialog_konsultation_create_personen}" icon="ui-icon-plusthick" title="#{messages.label_create}"
                  actionListener="#{personBean.prepareNewPerson()}"
                  update=":createPersonenDialog :growlForm:growl" resetValues="true"
                  oncomplete="PF('createPersonenDialogWidget').show()" partialSubmit="true" process="@this"
                  style="float:right;">
       </p:commandButton>
       
       <p:pickList id="konsultationPersonensPickList" var="person" itemLabel="#{person.id}"
                   value="#{konsultationBean.personens}" itemValue="#{person}"
                   showSourceFilter="true" showTargetFilter="true" filterMatchMode="contains" >
           <o:converter converterId="omnifaces.ListConverter" list="#{konsultationBean.fullPersonensList}"/>
         <p:ajax event="transfer" listener="#{konsultationBean.onPersonensPickListTransfer}" partialSubmit="true" process="@this" />
         <f:facet name="sourceCaption"><h:outputText value="#{messages.label_picklist_available}" /></f:facet>
         <f:facet name="targetCaption"><h:outputText value="#{messages.label_picklist_assigned}" /></f:facet>
       </p:pickList>
</h:panelGrid>
</html>

src/main/webapp/pages/konsultation/konsultationViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" >
        
        <h:outputText value="#{messages.field_label_konsultation_von}:" />
        <h:outputText value="#{konsultationBean.konsultation.von}" ><f:convertDateTime /></h:outputText>

        <h:outputText value="#{messages.field_label_konsultation_bis}:" />
        <h:outputText value="#{konsultationBean.konsultation.bis}" ><f:convertDateTime /></h:outputText>

        <h:outputText value="#{messages.field_label_konsultation_text}:" />
        <h:outputText value="#{konsultationBean.konsultation.text}" />

        <h:outputText value="#{messages.field_label_konsultation_aufenthalt}:" />
        <h:outputText value="#{konsultationBean.konsultation.aufenthalt.id}" />

    </h:panelGrid>
</html>