src/main/java/ch/ultrasoft/web/BelegungBean.java
package ch.ultrasoft.web;

import ch.ultrasoft.domain.AufenthaltEntity;
import ch.ultrasoft.domain.BelegungEntity;
import ch.ultrasoft.domain.ZelleEntity;
import ch.ultrasoft.service.AufenthaltService;
import ch.ultrasoft.service.BelegungService;
import ch.ultrasoft.service.ZelleService;
import ch.ultrasoft.web.util.MessageFactory;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

@Named("belegungBean")
@ViewScoped
public class BelegungBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(BelegungBean.class.getName());
    
    private List<BelegungEntity> belegungList;

    private BelegungEntity belegung;
    
    @Inject
    private BelegungService belegungService;
    
    @Inject
    private ZelleService zelleService;
    
    @Inject
    private AufenthaltService aufenthaltService;
    
    private List<ZelleEntity> allZellesList;
    
    private List<AufenthaltEntity> allAufenthaltsList;
    
    public void prepareNewBelegung() {
        reset();
        this.belegung = new BelegungEntity();
        // set any default values now, if you need
        // Example: this.belegung.setAnything("test");
    }

    public String persist() {

        String message;
        
        try {
            
            if (belegung.getId() != null) {
                belegung = belegungService.update(belegung);
                message = "message_successfully_updated";
            } else {
                belegung = belegungService.save(belegung);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        
        belegungList = null;

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        
        return null;
    }
    
    public String delete() {
        
        String message;
        
        try {
            belegungService.delete(belegung);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));
        
        return null;
    }
    
    public void onDialogOpen(BelegungEntity belegung) {
        reset();
        this.belegung = belegung;
    }
    
    public void reset() {
        belegung = null;
        belegungList = null;
        
        allZellesList = null;
        
        allAufenthaltsList = null;
        
    }

    // Get a List of all zelle
    public List<ZelleEntity> getZelles() {
        if (this.allZellesList == null) {
            this.allZellesList = zelleService.findAllZelleEntities();
        }
        return this.allZellesList;
    }
    
    // Update zelle of the current belegung
    public void updateZelle(ZelleEntity zelle) {
        this.belegung.setZelle(zelle);
        // Maybe we just created and assigned a new zelle. So reset the allZelleList.
        allZellesList = null;
    }
    
    // Get a List of all aufenthalt
    public List<AufenthaltEntity> getAufenthalts() {
        if (this.allAufenthaltsList == null) {
            this.allAufenthaltsList = aufenthaltService.findAllAufenthaltEntities();
        }
        return this.allAufenthaltsList;
    }
    
    // Update aufenthalt of the current belegung
    public void updateAufenthalt(AufenthaltEntity aufenthalt) {
        this.belegung.setAufenthalt(aufenthalt);
        // Maybe we just created and assigned a new aufenthalt. So reset the allAufenthaltList.
        allAufenthaltsList = null;
    }
    
    public BelegungEntity getBelegung() {
        if (this.belegung == null) {
            prepareNewBelegung();
        }
        return this.belegung;
    }
    
    public void setBelegung(BelegungEntity belegung) {
        this.belegung = belegung;
    }
    
    public List<BelegungEntity> getBelegungList() {
        if (belegungList == null) {
            belegungList = belegungService.findAllBelegungEntities();
        }
        return belegungList;
    }

    public void setBelegungList(List<BelegungEntity> belegungList) {
        this.belegungList = belegungList;
    }
    
}

src/main/webapp/pages/belegung/belegung.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">

    <h:form prependId="false" id="belegungDataForm" onkeypress="if (event.keyCode == 13) {return false; }">

        <p:dataTable id="belegungTable" value="#{belegungBean.belegungList}" var="belegung" resizableColumns="true" paginator="true"
                paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true"
                paginatorPosition="bottom" widgetVar="belegungTable" emptyMessage="#{messages.label_no_records_found}"
                reflow="true">
        
          <f:facet name="header" >

              <p:commandButton value="#{messages.create_new_belegung}" icon="ui-icon-plusthick" action="#{belegungBean.prepareNewBelegung()}"
                      resetValues="true" update=":editBelegungDialog" oncomplete="PF('editBelegungDialogWidget').show()"
                      style="float:left" />
              
              <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
              <p:columnToggler datasource="belegungTable" trigger="toggler" />
          </f:facet>
          
          <p:column headerText="#{messages.field_label_belegung_von}" sortBy="#{belegung.von}" filterBy="#{belegung.von}">
            <f:facet name="filter">
                <p:inputText id="vonFilter"
                        onkeyup="if (event.keyCode == 13) {PF('belegungTable').filter(); updateVonFilter(); return false;}" >
                    <p:remoteCommand name="updateVonFilter" update="belegungTable:vonFilter" />
                    <f:convertDateTime />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{belegung.von}"><f:convertDateTime /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_belegung_bis}" sortBy="#{belegung.bis}" filterBy="#{belegung.bis}">
            <f:facet name="filter">
                <p:inputText id="bisFilter"
                        onkeyup="if (event.keyCode == 13) {PF('belegungTable').filter(); updateBisFilter(); return false;}" >
                    <p:remoteCommand name="updateBisFilter" update="belegungTable:bisFilter" />
                    <f:convertDateTime />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{belegung.bis}"><f:convertDateTime /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_belegung_zelle}" sortBy="#{belegung.zelle}" filterBy="#{belegung.zelle}">
            <f:facet name="filter">
            <p:selectOneMenu  id="zelleFilter"
                            style="width:145px;"
                            onchange="PF('belegungTable').filter(); return false;">
                <f:selectItem noSelectionOption="true" itemLabel="" />
                <f:selectItems itemLabel="#{zelle.id}"
                            value="#{belegungBean.zelles}" 
                            var="zelle" 
                            itemValue="#{zelle}" />
                <o:converter converterId="omnifaces.SelectItemsConverter" list="#{belegungBean.zelles}" />
            </p:selectOneMenu>
            </f:facet>
            <h:outputText value="#{belegung.zelle.id}" />
          </p:column>

          <p:column headerText="#{messages.field_label_belegung_aufenthalt}" sortBy="#{belegung.aufenthalt}" filterBy="#{belegung.aufenthalt}">
            <f:facet name="filter">
            <p:selectOneMenu  id="aufenthaltFilter"
                            style="width:145px;"
                            onchange="PF('belegungTable').filter(); return false;">
                <f:selectItem noSelectionOption="true" itemLabel="" />
                <f:selectItems itemLabel="#{aufenthalt.id}"
                            value="#{belegungBean.aufenthalts}" 
                            var="aufenthalt" 
                            itemValue="#{aufenthalt}" />
                <o:converter converterId="omnifaces.SelectItemsConverter" list="#{belegungBean.aufenthalts}" />
            </p:selectOneMenu>
            </f:facet>
            <h:outputText value="#{belegung.aufenthalt.id}" />
          </p:column>

          <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">
            
            <p:commandButton icon="ui-icon-zoomin" update=":viewBelegungDialog" oncomplete="PF('viewBelegungDialogWidget').show()" title="#{messages.label_view}">
              <f:setPropertyActionListener value="#{belegung}" target="#{belegungBean.belegung}" />
            </p:commandButton>

            <p:commandButton icon="ui-icon-pencil" update=":editBelegungDialog"
                resetValues="true" 
                action="#{belegungBean.onDialogOpen(belegung)}"
                oncomplete="PF('editBelegungDialogWidget').show()"
                title="#{messages.label_edit}" >
            </p:commandButton>

            <p:commandButton icon="ui-icon-close" 
                oncomplete="PF('deleteBelegungDialogWidget').show()"
                title="#{messages.label_delete}" >
                <f:setPropertyActionListener value="#{belegung}"
                    target="#{belegungBean.belegung}" />
            </p:commandButton>
    
          </p:column>
          
        </p:dataTable>
        
    </h:form>

    <p:confirmDialog id="deleteBelegungDialog" widgetVar="deleteBelegungDialogWidget"
        header="#{messages.label_confirm_deletion}"
        severity="alarm">
        <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
        <p:outputPanel>
          <h:form>
            <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_yes}" action="#{belegungBean.delete}" update=":belegungDataForm :growlForm:growl" oncomplete="PF('deleteBelegungDialogWidget').hide()" />
              <p:commandButton value="#{messages.label_no}" onclick="PF('deleteBelegungDialogWidget').hide()" type="button" />
            </div>
          </h:form>
        </p:outputPanel>
    </p:confirmDialog>
    
    <p:dialog dynamic="true" id="editBelegungDialog" header="#{messages.label_belegung_caption}"
            modal="true" widgetVar="editBelegungDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{belegungBean.reset}"/>
        <h:form id="editBelegungForm" >
            <p:outputPanel id="belegungEditPanel">
                <ui:include src="/pages/belegung/belegungEditInclude.xhtml"/>
                <div style="text-align: center; margin:10px">
                    <p:commandButton value="#{messages.label_save}"
                            icon="ui-icon-disk" action="#{belegungBean.persist}"
                            update=":editBelegungForm:belegungEditPanel :belegungDataForm :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('editBelegungDialogWidget').hide()" />
                    <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('editBelegungDialogWidget').hide()" type="button" />
                </div>
            </p:outputPanel>
        </h:form>
    </p:dialog>
    
    <p:dialog dynamic="true" id="viewBelegungDialog" header="#{messages.label_belegung_caption}" modal="true" widgetVar="viewBelegungDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{belegungBean.reset}" />
        <h:form id="viewBelegungForm">
          <ui:include src="/pages/belegung/belegungViewInclude.xhtml"/>
          <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('viewBelegungDialogWidget').hide()" type="button" />
          </div>
        </h:form>
    </p:dialog>
    
    <p:dialog dynamic="true" id="createZelleFromEditDialog"
        header="#{messages.dialog_belegung_create_zelle}" modal="true"
        widgetVar="createZelleFromEditDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{zelleBean.reset}" />
        <p:outputPanel id="createZellePanel">
                <h:form id="createZelleForm">
                    <ui:include src="/pages/zelle/zelleEditInclude.xhtml">
                        <ui:param name="hideBelegungSelectInput" value="true" />
                    </ui:include>
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton
                            action="#{belegungBean.updateZelle(zelleBean.zelle)}"
                            value="#{messages.label_save}" icon="ui-icon-disk"
                            actionListener="#{zelleBean.persist}"
                            update=":editBelegungForm:zelleSelectInput :createZellePanel :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('createZelleFromEditDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_close}"
                            icon="ui-icon-close"
                            onclick="PF('createZelleFromEditDialogWidget').hide()"
                            type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
    </p:dialog>
    
    <p:dialog dynamic="true" id="createAufenthaltFromEditDialog"
        header="#{messages.dialog_belegung_create_aufenthalt}" modal="true"
        widgetVar="createAufenthaltFromEditDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{aufenthaltBean.reset}" />
        <p:outputPanel id="createAufenthaltPanel">
                <h:form id="createAufenthaltForm">
                    <ui:include src="/pages/aufenthalt/aufenthaltEditInclude.xhtml">
                        <ui:param name="hideBelegungSelectInput" value="true" />
                    </ui:include>
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton
                            action="#{belegungBean.updateAufenthalt(aufenthaltBean.aufenthalt)}"
                            value="#{messages.label_save}" icon="ui-icon-disk"
                            actionListener="#{aufenthaltBean.persist}"
                            update=":editBelegungForm:aufenthaltSelectInput :createAufenthaltPanel :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('createAufenthaltFromEditDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_close}"
                            icon="ui-icon-close"
                            onclick="PF('createAufenthaltFromEditDialogWidget').hide()"
                            type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
    </p:dialog>
    
  </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/belegung/belegungEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

        <p:outputPanel styleClass="ui-fluid">

            <p:panelGrid columns="3" columnClasses="ui-grid-col-4,ui-grid-col-6,ui-grid-col-2" layout="grid" style="max-width:400px">
            
                <h:outputLabel value="#{messages.field_label_belegung_von}:" for="vonEditInput" />
                <p:calendar id="vonEditInput" navigator="true" value="#{belegungBean.belegung.von}" label="#{messages.field_label_belegung_von}" />
                <p:message for="vonEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_belegung_bis}:" for="bisEditInput" />
                <p:calendar id="bisEditInput" navigator="true" value="#{belegungBean.belegung.bis}" label="#{messages.field_label_belegung_bis}" />
                <p:message for="bisEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_belegung_zelle}:" for="zelleSelectInput" rendered="#{not hideZelleSelectInput}"/>
                <h:panelGroup rendered="#{not hideZelleSelectInput}">
                    <p:selectOneMenu value="#{belegungBean.belegung.zelle}"
                                    id="zelleSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{belegungBean.zelles}" 
                                    var="zelle" 
                                    itemLabel="#{zelle.id}"
                                    itemValue="#{zelle}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{belegungBean.zelles}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hideZelleSelectInput}">
                
                    <p:commandButton icon="ui-icon-plusthick" title="#{messages.label_create}"
                              action="#{zelleBean.prepareNewZelle()}"
                              update=":createZelleFromEditDialog"
                              resetValues="true"
                              oncomplete="PF('createZelleFromEditDialogWidget').show()"
                              rendered="#{applicationBean.componentExists('createZelleFromEditDialog')}"
                              style="vertical-align:top;" partialSubmit="true" process="@this">
                    </p:commandButton>
                    
                    <p:message for="zelleSelectInput" display="icon" rendered="#{not hideZelleSelectInput}"/>
                </h:panelGroup>
                
                <h:outputLabel value="#{messages.field_label_belegung_aufenthalt}:" for="aufenthaltSelectInput" rendered="#{not hideAufenthaltSelectInput}"/>
                <h:panelGroup rendered="#{not hideAufenthaltSelectInput}">
                    <p:selectOneMenu value="#{belegungBean.belegung.aufenthalt}"
                                    id="aufenthaltSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{belegungBean.aufenthalts}" 
                                    var="aufenthalt" 
                                    itemLabel="#{aufenthalt.id}"
                                    itemValue="#{aufenthalt}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{belegungBean.aufenthalts}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hideAufenthaltSelectInput}">
                
                    <p:commandButton icon="ui-icon-plusthick" title="#{messages.label_create}"
                              action="#{aufenthaltBean.prepareNewAufenthalt()}"
                              update=":createAufenthaltFromEditDialog"
                              resetValues="true"
                              oncomplete="PF('createAufenthaltFromEditDialogWidget').show()"
                              rendered="#{applicationBean.componentExists('createAufenthaltFromEditDialog')}"
                              style="vertical-align:top;" partialSubmit="true" process="@this">
                    </p:commandButton>
                    
                    <p:message for="aufenthaltSelectInput" display="icon" rendered="#{not hideAufenthaltSelectInput}"/>
                </h:panelGroup>
                
            </p:panelGrid>

        </p:outputPanel>
</html>

src/main/webapp/pages/belegung/belegungViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" >
        
        <h:outputText value="#{messages.field_label_belegung_von}:" />
        <h:outputText value="#{belegungBean.belegung.von}" ><f:convertDateTime /></h:outputText>

        <h:outputText value="#{messages.field_label_belegung_bis}:" />
        <h:outputText value="#{belegungBean.belegung.bis}" ><f:convertDateTime /></h:outputText>

        <h:outputText value="#{messages.field_label_belegung_zelle}:" />
        <h:outputText value="#{belegungBean.belegung.zelle.id}" />

        <h:outputText value="#{messages.field_label_belegung_aufenthalt}:" />
        <h:outputText value="#{belegungBean.belegung.aufenthalt.id}" />

    </h:panelGrid>
</html>