src/main/java/ch/ultrasoft/web/InsasseBean.java
package ch.ultrasoft.web;

import ch.ultrasoft.domain.InsasseEntity;
import ch.ultrasoft.domain.PersonEntity;
import ch.ultrasoft.service.InsasseService;
import ch.ultrasoft.service.PersonService;
import ch.ultrasoft.web.util.MessageFactory;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

@Named("insasseBean")
@ViewScoped
public class InsasseBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(InsasseBean.class.getName());
    
    private List<InsasseEntity> insasseList;

    private InsasseEntity insasse;
    
    @Inject
    private InsasseService insasseService;
    
    @Inject
    private PersonService personService;
    
    private List<PersonEntity> allPersonsList;
    
    public void prepareNewInsasse() {
        reset();
        this.insasse = new InsasseEntity();
        // set any default values now, if you need
        // Example: this.insasse.setAnything("test");
    }

    public String persist() {

        String message;
        
        try {
            
            if (insasse.getId() != null) {
                insasse = insasseService.update(insasse);
                message = "message_successfully_updated";
            } else {
                insasse = insasseService.save(insasse);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        
        insasseList = null;

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        
        return null;
    }
    
    public String delete() {
        
        String message;
        
        try {
            insasseService.delete(insasse);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));
        
        return null;
    }
    
    public void onDialogOpen(InsasseEntity insasse) {
        reset();
        this.insasse = insasse;
    }
    
    public void reset() {
        insasse = null;
        insasseList = null;
        
        allPersonsList = null;
        
    }

    // Get a List of all person
    public List<PersonEntity> getPersons() {
        if (this.allPersonsList == null) {
            this.allPersonsList = personService.findAllPersonEntities();
        }
        return this.allPersonsList;
    }
    
    // Update person of the current insasse
    public void updatePerson(PersonEntity person) {
        this.insasse.setPerson(person);
        // Maybe we just created and assigned a new person. So reset the allPersonList.
        allPersonsList = null;
    }
    
    public InsasseEntity getInsasse() {
        if (this.insasse == null) {
            prepareNewInsasse();
        }
        return this.insasse;
    }
    
    public void setInsasse(InsasseEntity insasse) {
        this.insasse = insasse;
    }
    
    public List<InsasseEntity> getInsasseList() {
        if (insasseList == null) {
            insasseList = insasseService.findAllInsasseEntities();
        }
        return insasseList;
    }

    public void setInsasseList(List<InsasseEntity> insasseList) {
        this.insasseList = insasseList;
    }
    
}

src/main/webapp/pages/insasse/insasse.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">

    <h:form prependId="false" id="insasseDataForm" onkeypress="if (event.keyCode == 13) {return false; }">

        <p:dataTable id="insasseTable" value="#{insasseBean.insasseList}" var="insasse" resizableColumns="true" paginator="true"
                paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true"
                paginatorPosition="bottom" widgetVar="insasseTable" emptyMessage="#{messages.label_no_records_found}"
                reflow="true">
        
          <f:facet name="header" >

              <p:commandButton value="#{messages.create_new_insasse}" icon="ui-icon-plusthick" action="#{insasseBean.prepareNewInsasse()}"
                      resetValues="true" update=":editInsasseDialog" oncomplete="PF('editInsasseDialogWidget').show()"
                      style="float:left" />
              
              <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
              <p:columnToggler datasource="insasseTable" trigger="toggler" />
          </f:facet>
          
          <p:column headerText="#{messages.field_label_insasse_person}" sortBy="#{insasse.person}" filterBy="#{insasse.person}">
            <f:facet name="filter">
            <p:selectOneMenu  id="personFilter"
                            style="width:145px;"
                            onchange="PF('insasseTable').filter(); return false;">
                <f:selectItem noSelectionOption="true" itemLabel="" />
                <f:selectItems itemLabel="#{person.id}"
                            value="#{insasseBean.persons}" 
                            var="person" 
                            itemValue="#{person}" />
                <o:converter converterId="omnifaces.SelectItemsConverter" list="#{insasseBean.persons}" />
            </p:selectOneMenu>
            </f:facet>
            <h:outputText value="#{insasse.person.id}" />
          </p:column>

          <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">
            
            <p:commandButton icon="ui-icon-zoomin" update=":viewInsasseDialog" oncomplete="PF('viewInsasseDialogWidget').show()" title="#{messages.label_view}">
              <f:setPropertyActionListener value="#{insasse}" target="#{insasseBean.insasse}" />
            </p:commandButton>

            <p:commandButton icon="ui-icon-pencil" update=":editInsasseDialog"
                resetValues="true" 
                action="#{insasseBean.onDialogOpen(insasse)}"
                oncomplete="PF('editInsasseDialogWidget').show()"
                title="#{messages.label_edit}" >
            </p:commandButton>

            <p:commandButton icon="ui-icon-close" 
                oncomplete="PF('deleteInsasseDialogWidget').show()"
                title="#{messages.label_delete}" >
                <f:setPropertyActionListener value="#{insasse}"
                    target="#{insasseBean.insasse}" />
            </p:commandButton>
    
          </p:column>
          
        </p:dataTable>
        
    </h:form>

    <p:confirmDialog id="deleteInsasseDialog" widgetVar="deleteInsasseDialogWidget"
        header="#{messages.label_confirm_deletion}"
        severity="alarm">
        <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
        <p:outputPanel>
          <h:form>
            <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_yes}" action="#{insasseBean.delete}" update=":insasseDataForm :growlForm:growl" oncomplete="PF('deleteInsasseDialogWidget').hide()" />
              <p:commandButton value="#{messages.label_no}" onclick="PF('deleteInsasseDialogWidget').hide()" type="button" />
            </div>
          </h:form>
        </p:outputPanel>
    </p:confirmDialog>
    
    <p:dialog dynamic="true" id="editInsasseDialog" header="#{messages.label_insasse_caption}"
            modal="true" widgetVar="editInsasseDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{insasseBean.reset}"/>
        <h:form id="editInsasseForm" >
            <p:outputPanel id="insasseEditPanel">
                <ui:include src="/pages/insasse/insasseEditInclude.xhtml"/>
                <div style="text-align: center; margin:10px">
                    <p:commandButton value="#{messages.label_save}"
                            icon="ui-icon-disk" action="#{insasseBean.persist}"
                            update=":editInsasseForm:insasseEditPanel :insasseDataForm :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('editInsasseDialogWidget').hide()" />
                    <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('editInsasseDialogWidget').hide()" type="button" />
                </div>
            </p:outputPanel>
        </h:form>
    </p:dialog>
    
    <p:dialog dynamic="true" id="viewInsasseDialog" header="#{messages.label_insasse_caption}" modal="true" widgetVar="viewInsasseDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{insasseBean.reset}" />
        <h:form id="viewInsasseForm">
          <ui:include src="/pages/insasse/insasseViewInclude.xhtml"/>
          <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('viewInsasseDialogWidget').hide()" type="button" />
          </div>
        </h:form>
    </p:dialog>
    
    <p:dialog dynamic="true" id="createPersonFromEditDialog"
        header="#{messages.dialog_insasse_create_person}" modal="true"
        widgetVar="createPersonFromEditDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{personBean.reset}" />
        <p:outputPanel id="createPersonPanel">
                <h:form id="createPersonForm">
                    <ui:include src="/pages/person/personEditInclude.xhtml">
                        <ui:param name="hideInsasseSelectInput" value="true" />
                    </ui:include>
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton
                            action="#{insasseBean.updatePerson(personBean.person)}"
                            value="#{messages.label_save}" icon="ui-icon-disk"
                            actionListener="#{personBean.persist}"
                            update=":editInsasseForm:personSelectInput :createPersonPanel :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('createPersonFromEditDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_close}"
                            icon="ui-icon-close"
                            onclick="PF('createPersonFromEditDialogWidget').hide()"
                            type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
    </p:dialog>
    
  </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/insasse/insasseEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

        <p:outputPanel styleClass="ui-fluid">

            <p:panelGrid columns="3" columnClasses="ui-grid-col-4,ui-grid-col-6,ui-grid-col-2" layout="grid" style="max-width:400px">
            
                <h:outputLabel value="#{messages.field_label_insasse_person}:" for="personSelectInput" rendered="#{not hidePersonSelectInput}"/>
                <h:panelGroup rendered="#{not hidePersonSelectInput}">
                    <p:selectOneMenu value="#{insasseBean.insasse.person}"
                                    id="personSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{insasseBean.persons}" 
                                    var="person" 
                                    itemLabel="#{person.id}"
                                    itemValue="#{person}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{insasseBean.persons}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hidePersonSelectInput}">
                
                    <p:commandButton icon="ui-icon-plusthick" title="#{messages.label_create}"
                              action="#{personBean.prepareNewPerson()}"
                              update=":createPersonFromEditDialog"
                              resetValues="true"
                              oncomplete="PF('createPersonFromEditDialogWidget').show()"
                              rendered="#{applicationBean.componentExists('createPersonFromEditDialog')}"
                              style="vertical-align:top;" partialSubmit="true" process="@this">
                    </p:commandButton>
                    
                    <p:message for="personSelectInput" display="icon" rendered="#{not hidePersonSelectInput}"/>
                </h:panelGroup>
                
            </p:panelGrid>

        </p:outputPanel>
</html>

src/main/webapp/pages/insasse/insasseViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" >
        
        <h:outputText value="#{messages.field_label_insasse_person}:" />
        <h:outputText value="#{insasseBean.insasse.person.id}" />

    </h:panelGrid>
</html>