src/main/java/ch/ultrasoft/web/StrafeBean.java
package ch.ultrasoft.web;

import ch.ultrasoft.domain.StrafeEntity;
import ch.ultrasoft.domain.UrteilEntity;
import ch.ultrasoft.service.StrafeService;
import ch.ultrasoft.service.UrteilService;
import ch.ultrasoft.web.util.MessageFactory;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

@Named("strafeBean")
@ViewScoped
public class StrafeBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(StrafeBean.class.getName());
    
    private List<StrafeEntity> strafeList;

    private StrafeEntity strafe;
    
    @Inject
    private StrafeService strafeService;
    
    @Inject
    private UrteilService urteilService;
    
    private List<UrteilEntity> allUrteilsList;
    
    public void prepareNewStrafe() {
        reset();
        this.strafe = new StrafeEntity();
        // set any default values now, if you need
        // Example: this.strafe.setAnything("test");
    }

    public String persist() {

        String message;
        
        try {
            
            if (strafe.getId() != null) {
                strafe = strafeService.update(strafe);
                message = "message_successfully_updated";
            } else {
                strafe = strafeService.save(strafe);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        
        strafeList = null;

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        
        return null;
    }
    
    public String delete() {
        
        String message;
        
        try {
            strafeService.delete(strafe);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));
        
        return null;
    }
    
    public void onDialogOpen(StrafeEntity strafe) {
        reset();
        this.strafe = strafe;
    }
    
    public void reset() {
        strafe = null;
        strafeList = null;
        
        allUrteilsList = null;
        
    }

    // Get a List of all urteil
    public List<UrteilEntity> getUrteils() {
        if (this.allUrteilsList == null) {
            this.allUrteilsList = urteilService.findAllUrteilEntities();
        }
        return this.allUrteilsList;
    }
    
    // Update urteil of the current strafe
    public void updateUrteil(UrteilEntity urteil) {
        this.strafe.setUrteil(urteil);
        // Maybe we just created and assigned a new urteil. So reset the allUrteilList.
        allUrteilsList = null;
    }
    
    public StrafeEntity getStrafe() {
        if (this.strafe == null) {
            prepareNewStrafe();
        }
        return this.strafe;
    }
    
    public void setStrafe(StrafeEntity strafe) {
        this.strafe = strafe;
    }
    
    public List<StrafeEntity> getStrafeList() {
        if (strafeList == null) {
            strafeList = strafeService.findAllStrafeEntities();
        }
        return strafeList;
    }

    public void setStrafeList(List<StrafeEntity> strafeList) {
        this.strafeList = strafeList;
    }
    
}

src/main/webapp/pages/strafe/strafe.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">

    <h:form prependId="false" id="strafeDataForm" onkeypress="if (event.keyCode == 13) {return false; }">

        <p:dataTable id="strafeTable" value="#{strafeBean.strafeList}" var="strafe" resizableColumns="true" paginator="true"
                paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true"
                paginatorPosition="bottom" widgetVar="strafeTable" emptyMessage="#{messages.label_no_records_found}"
                reflow="true">
        
          <f:facet name="header" >

              <p:commandButton value="#{messages.create_new_strafe}" icon="ui-icon-plusthick" action="#{strafeBean.prepareNewStrafe()}"
                      resetValues="true" update=":editStrafeDialog" oncomplete="PF('editStrafeDialogWidget').show()"
                      style="float:left" />
              
              <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
              <p:columnToggler datasource="strafeTable" trigger="toggler" />
          </f:facet>
          
          <p:column  headerText="#{messages.field_label_strafe_text}" sortBy="#{strafe.text}" filterBy="#{strafe.text}">
            <f:facet name="filter">
                <p:inputText id="textFilter"
                        onkeypress="if (event.keyCode == 13) {PF('strafeTable').filter(); updateTextFilter(); return false; }" >
                    <p:remoteCommand name="updateTextFilter" update="strafeTable:textFilter" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{strafe.text}" />
          </p:column>

          <p:column headerText="#{messages.field_label_strafe_urteil}" sortBy="#{strafe.urteil}" filterBy="#{strafe.urteil}">
            <f:facet name="filter">
            <p:selectOneMenu  id="urteilFilter"
                            style="width:145px;"
                            onchange="PF('strafeTable').filter(); return false;">
                <f:selectItem noSelectionOption="true" itemLabel="" />
                <f:selectItems itemLabel="#{urteil.id}"
                            value="#{strafeBean.urteils}" 
                            var="urteil" 
                            itemValue="#{urteil}" />
                <o:converter converterId="omnifaces.SelectItemsConverter" list="#{strafeBean.urteils}" />
            </p:selectOneMenu>
            </f:facet>
            <h:outputText value="#{strafe.urteil.id}" />
          </p:column>

          <p:column headerText="#{messages.field_label_strafe_tage}" sortBy="#{strafe.tage}" filterBy="#{strafe.tage}">
            <f:facet name="filter">
                <p:inputText id="tageFilter"
                        onkeypress="if (event.keyCode == 13) {PF('strafeTable').filter(); updateTageFilter(); return false; }" >
                    <p:remoteCommand name="updateTageFilter" update="strafeTable:tageFilter" />
                    <f:convertNumber integerOnly="true" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{strafe.tage}" ><f:convertNumber /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_strafe_monate}" sortBy="#{strafe.monate}" filterBy="#{strafe.monate}">
            <f:facet name="filter">
                <p:inputText id="monateFilter"
                        onkeypress="if (event.keyCode == 13) {PF('strafeTable').filter(); updateMonateFilter(); return false; }" >
                    <p:remoteCommand name="updateMonateFilter" update="strafeTable:monateFilter" />
                    <f:convertNumber integerOnly="true" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{strafe.monate}" ><f:convertNumber /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_strafe_jahre}" sortBy="#{strafe.jahre}" filterBy="#{strafe.jahre}">
            <f:facet name="filter">
                <p:inputText id="jahreFilter"
                        onkeypress="if (event.keyCode == 13) {PF('strafeTable').filter(); updateJahreFilter(); return false; }" >
                    <p:remoteCommand name="updateJahreFilter" update="strafeTable:jahreFilter" />
                    <f:convertNumber integerOnly="true" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{strafe.jahre}" ><f:convertNumber /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_strafe_addieren}" sortBy="#{strafe.addieren}" filterBy="#{strafe.addieren}" exportable="false">
            <f:facet name="filter">
                 <p:selectOneMenu converter="javax.faces.Boolean"
                        onchange="PF('strafeTable').filter(); return false;" style="width:50%">
                        <f:selectItem itemLabel="&nbsp;" itemValue="" />
                        <f:selectItem itemLabel="#{messages.field_label_strafe_addieren_true}" itemValue="true" />
                        <f:selectItem itemLabel="#{messages.field_label_strafe_addieren_false}" itemValue="false" />
                </p:selectOneMenu>
            </f:facet>
            <h:panelGroup styleClass="ui-icon ui-icon-check" rendered="#{strafe.addieren}"/>
          </p:column>

          <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">
            
            <p:commandButton icon="ui-icon-zoomin" update=":viewStrafeDialog" oncomplete="PF('viewStrafeDialogWidget').show()" title="#{messages.label_view}">
              <f:setPropertyActionListener value="#{strafe}" target="#{strafeBean.strafe}" />
            </p:commandButton>

            <p:commandButton icon="ui-icon-pencil" update=":editStrafeDialog"
                resetValues="true" 
                action="#{strafeBean.onDialogOpen(strafe)}"
                oncomplete="PF('editStrafeDialogWidget').show()"
                title="#{messages.label_edit}" >
            </p:commandButton>

            <p:commandButton icon="ui-icon-close" 
                oncomplete="PF('deleteStrafeDialogWidget').show()"
                title="#{messages.label_delete}" >
                <f:setPropertyActionListener value="#{strafe}"
                    target="#{strafeBean.strafe}" />
            </p:commandButton>
    
          </p:column>
          
        </p:dataTable>
        
    </h:form>

    <p:confirmDialog id="deleteStrafeDialog" widgetVar="deleteStrafeDialogWidget"
        header="#{messages.label_confirm_deletion}"
        severity="alarm">
        <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
        <p:outputPanel>
          <h:form>
            <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_yes}" action="#{strafeBean.delete}" update=":strafeDataForm :growlForm:growl" oncomplete="PF('deleteStrafeDialogWidget').hide()" />
              <p:commandButton value="#{messages.label_no}" onclick="PF('deleteStrafeDialogWidget').hide()" type="button" />
            </div>
          </h:form>
        </p:outputPanel>
    </p:confirmDialog>
    
    <p:dialog dynamic="true" id="editStrafeDialog" header="#{messages.label_strafe_caption}"
            modal="true" widgetVar="editStrafeDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{strafeBean.reset}"/>
        <h:form id="editStrafeForm" >
            <p:outputPanel id="strafeEditPanel">
                <ui:include src="/pages/strafe/strafeEditInclude.xhtml"/>
                <div style="text-align: center; margin:10px">
                    <p:commandButton value="#{messages.label_save}"
                            icon="ui-icon-disk" action="#{strafeBean.persist}"
                            update=":editStrafeForm:strafeEditPanel :strafeDataForm :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('editStrafeDialogWidget').hide()" />
                    <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('editStrafeDialogWidget').hide()" type="button" />
                </div>
            </p:outputPanel>
        </h:form>
    </p:dialog>
    
    <p:dialog dynamic="true" id="viewStrafeDialog" header="#{messages.label_strafe_caption}" modal="true" widgetVar="viewStrafeDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{strafeBean.reset}" />
        <h:form id="viewStrafeForm">
          <ui:include src="/pages/strafe/strafeViewInclude.xhtml"/>
          <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" onclick="PF('viewStrafeDialogWidget').hide()" type="button" />
          </div>
        </h:form>
    </p:dialog>
    
    <p:dialog dynamic="true" id="createUrteilFromEditDialog"
        header="#{messages.dialog_strafe_create_urteil}" modal="true"
        widgetVar="createUrteilFromEditDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{urteilBean.reset}" />
        <p:outputPanel id="createUrteilPanel">
                <h:form id="createUrteilForm">
                    <ui:include src="/pages/urteil/urteilEditInclude.xhtml">
                        <ui:param name="hideStrafeSelectInput" value="true" />
                    </ui:include>
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton
                            action="#{strafeBean.updateUrteil(urteilBean.urteil)}"
                            value="#{messages.label_save}" icon="ui-icon-disk"
                            actionListener="#{urteilBean.persist}"
                            update=":editStrafeForm:urteilSelectInput :createUrteilPanel :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('createUrteilFromEditDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_close}"
                            icon="ui-icon-close"
                            onclick="PF('createUrteilFromEditDialogWidget').hide()"
                            type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
    </p:dialog>
    
  </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/strafe/strafeEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

        <p:outputPanel styleClass="ui-fluid">

            <p:panelGrid columns="3" columnClasses="ui-grid-col-4,ui-grid-col-6,ui-grid-col-2" layout="grid" style="max-width:400px">
            
                <h:outputLabel value="#{messages.field_label_strafe_text}:" for="textEditInput" />
                <p:inputText value="#{strafeBean.strafe.text}" id="textEditInput" 
                    label="#{messages.field_label_strafe_text}" />
                <p:message for="textEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_strafe_urteil}:" for="urteilSelectInput" rendered="#{not hideUrteilSelectInput}"/>
                <h:panelGroup rendered="#{not hideUrteilSelectInput}">
                    <p:selectOneMenu value="#{strafeBean.strafe.urteil}"
                                    id="urteilSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{strafeBean.urteils}" 
                                    var="urteil" 
                                    itemLabel="#{urteil.id}"
                                    itemValue="#{urteil}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{strafeBean.urteils}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hideUrteilSelectInput}">
                
                    <p:commandButton icon="ui-icon-plusthick" title="#{messages.label_create}"
                              action="#{urteilBean.prepareNewUrteil()}"
                              update=":createUrteilFromEditDialog"
                              resetValues="true"
                              oncomplete="PF('createUrteilFromEditDialogWidget').show()"
                              rendered="#{applicationBean.componentExists('createUrteilFromEditDialog')}"
                              style="vertical-align:top;" partialSubmit="true" process="@this">
                    </p:commandButton>
                    
                    <p:message for="urteilSelectInput" display="icon" rendered="#{not hideUrteilSelectInput}"/>
                </h:panelGroup>
                
                <h:outputLabel value="#{messages.field_label_strafe_tage}:" for="tageEditInput" />
                <p:inputText value="#{strafeBean.strafe.tage}"  id="tageEditInput" 
                    label="#{messages.field_label_strafe_tage}" />
                <p:message for="tageEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_strafe_monate}:" for="monateEditInput" />
                <p:inputText value="#{strafeBean.strafe.monate}"  id="monateEditInput" 
                    label="#{messages.field_label_strafe_monate}" />
                <p:message for="monateEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_strafe_jahre}:" for="jahreEditInput" />
                <p:inputText value="#{strafeBean.strafe.jahre}"  id="jahreEditInput" 
                    label="#{messages.field_label_strafe_jahre}" />
                <p:message for="jahreEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_strafe_addieren}:" for="addierenInput" />
                <p:selectBooleanCheckbox value="#{strafeBean.strafe.addieren}" id="addierenInput" label="#{messages.field_label_strafe_addieren}" />
                <p:message for="addierenInput" display="icon" />

            </p:panelGrid>

        </p:outputPanel>
</html>

src/main/webapp/pages/strafe/strafeViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" >
        
        <h:outputText value="#{messages.field_label_strafe_text}:" />
        <h:outputText value="#{strafeBean.strafe.text}" />

        <h:outputText value="#{messages.field_label_strafe_urteil}:" />
        <h:outputText value="#{strafeBean.strafe.urteil.id}" />

        <h:outputText value="#{messages.field_label_strafe_tage}:" />
        <h:outputText value="#{strafeBean.strafe.tage}" />

        <h:outputText value="#{messages.field_label_strafe_monate}:" />
        <h:outputText value="#{strafeBean.strafe.monate}" />

        <h:outputText value="#{messages.field_label_strafe_jahre}:" />
        <h:outputText value="#{strafeBean.strafe.jahre}" />

        <h:outputText value="#{messages.field_label_strafe_addieren}:" />
        <p:selectBooleanCheckbox disabled="true" value="#{strafeBean.strafe.addieren}" id="addierenInput" />

    </h:panelGrid>
</html>